export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const MONSTERS_REQUEST_PENDING = 'MONSTERS_REQUEST_PENDING';
export const MONSTERS_REQUEST_SUCCESS = 'MONSTERS_REQUEST_SUCCESS';
export const MONSTERS_REQUEST_FAILED = 'MONSTERS_REQUEST_FAILED';
